clear; clc; close all;

% 1. Load all the parameters
params = All_Parameters();

% 2. Ground truth and Camera Setup
truth = Simulate_Ground_Truth_1(params);
cameras = Setup_Cameras_2(params);

% 3. Simulate Multi-camera Asynchronous Measurements 
[measurement_log, measurement_noise_std] = Simulate_Measurements_3( ...
    truth.true_trajectory_3D_1, ...
    truth.true_trajectory_3D_2, ...
    truth.time_vector, ...
    truth.num_steps, ...
    cameras.R_GCF_to_Cam1, cameras.t_GCF_to_Cam1, cameras.K_cam1, ...
    cameras.R_GCF_to_Cam2, cameras.t_GCF_to_Cam2, cameras.K_cam2, ...
    cameras.image_width, cameras.image_height, ...
    params.total_time);

% 4. Run EKF and IMM Filters 
[tracks, track_histories, track_colours] = Run_Tracker_4( ...
    measurement_log, measurement_noise_std, ...
    cameras.R_GCF_to_Cam1, cameras.t_GCF_to_Cam1, cameras.K_cam1, ...
    cameras.R_GCF_to_Cam2, cameras.t_GCF_to_Cam2, cameras.K_cam2, ...
    cameras.Projection_Cam1, cameras.Projection_Cam2, ...
    cameras.P_birth_default, params.tracker);

% 5. Visualise the trajectories + created Tracks 
Plot_All_Trajectories_5( ...
    truth.true_trajectory_3D_1, truth.true_trajectory_3D_2, ...
    track_histories, track_colours, ...
    cameras.camera1_position_GCF, cameras.camera2_position_GCF, ...
    cameras.R_GCF_to_Cam1, cameras.R_GCF_to_Cam2, ...
    cameras.K_cam1, cameras.K_cam2, ...
    cameras.image_width, cameras.image_height);
