% Processing real-world asynchronous camera data 
% Load real calibration data and real measurements from the Python
% script and use validated EKF pipeline to estimate the 3D trajectory

%% Section 1: Load All Calibration and Measurement Data
clear; clc; close all;

% 1. Calibration Parameters 
load('Stereo_Params.mat'); 

% Extract 
cameraParams1 = stereoParams.CameraParameters1;
cameraParams2 = stereoParams.CameraParameters2;

% Get the intrinsic matrices 
K_cam1 = cameraParams1.IntrinsicMatrix';
K_cam2 = cameraParams2.IntrinsicMatrix';

% Get the extrinsic parameters (the pose of Camera 2 relative to Camera 1)
% Define Camera 1 as global coordinate frame origin (GCF = Cam1)
R_GCF_to_Cam1 = eye(3);
t_GCF_to_Cam1 = [0; 0; 0];

% stereo calibration gives pose of Cam2 relative to Cam1
R_Cam1_to_Cam2 = stereoParams.RotationOfCamera2'; 
t_Cam1_to_Cam2 = stereoParams.TranslationOfCamera2'; 

% For the EKF, the pose of Cam2 is required in the GCF (which is Cam1's frame)
R_GCF_to_Cam2 = R_Cam1_to_Cam2;
t_GCF_to_Cam2 = -R_GCF_to_Cam2 * t_Cam1_to_Cam2;

disp('Stereo calibration parameters loaded successfully.');

% 2. Load real measurement data 
% Load the CSV file generated by Python script 
measurement_log = readmatrix('../../ThesisB_Object_Classification/camera_detections_YYYYMMDD_HHMMSS.csv'); % <--- UPDATE FILENAME
disp(['Loaded ', num2str(size(measurement_log, 1)), ' real-world measurements.']);

%% Section 2: Triangulation Initialization from Real Data

first_cam1_idx = find(measurement_log(:, 2) == 0, 1, 'first'); % Cam1_idx = 0
first_cam2_idx = find(measurement_log(:, 2) == 1, 1, 'first'); % Cam2_idx = 1

if isempty(first_cam1_idx) || isempty(first_cam2_idx)
    error('Could not find initial measurements from both cameras in the log file.');
end

meas1 = measurement_log(first_cam1_idx, :);
meas2 = measurement_log(first_cam2_idx, :);

max_time_diff = 0.2; % seconds
if abs(meas1(1) - meas2(1)) > max_time_diff
    error('Initial measurements are too far apart in time for triangulation.');
end

% Create the projection matrices using real loaded calibration data
P1 = K_cam1 * [R_GCF_to_Cam1, t_GCF_to_Cam1];
P2 = K_cam2 * [R_GCF_to_Cam2, t_GCF_to_Cam2];

% Triangulate to get the initial 3D position guess
initial_pos_guess = triangulate(meas1(3:4), meas2(3:4), P1', P2')';
initial_vel_guess = [0; 0; 0];

disp('EKF initialised from first triangulated point.');

%% Section 3: Event-Driven EKF Loop on Real Data

num_measurements = size(measurement_log, 1);
X_est = zeros(6, num_measurements);
X_est(:, 1) = [initial_pos_guess; initial_vel_guess];

P_est = diag([1^2, 1^2, 1^2, 5^2, 5^2, 5^2]); % Moderate pos unc, high vel unc
measurement_noise_std = 1.0; % pixels
R_ekf = diag([measurement_noise_std^2, measurement_noise_std^2]);

g = -9.81; % Acceleration due to gravity acting on the z-axis 

for k = 2:num_steps
    % Dynamic dt 
    dt = timestamps(k) - timestamps(k-1);
    
    % CV model 
    F_ekf = [1 0 0 dt 0 0; 
             0 1 0 0 dt 0; 
             0 0 1 0 0 dt;
             0 0 0 1 0 0; 
             0 0 0 0 1 0; 
             0 0 0 0 0 1];
    
    % G -> control input matrix. 
    % It maps the effect of gravity (u)
    % onto the state vector. 
    % Gravity affects Z-position by 0.5*g*t^2 and Z-velocity by g*t.
    G = [   0; 
            0; 
        0.5 * dt^2;
            0; 
            0; 
            dt      ];

    % Process Noise 
    % Q represents unmodelled forces such as drag
    unmodelled_accel_std = 0.5; % m/s^2
    q_pos = (0.5 * unmodelled_accel_std * dt^2)^2;
    q_vel = (unmodelled_accel_std * dt)^2;
    Q_ekf = diag([q_pos, q_pos, q_pos, q_vel, q_vel, q_vel]);

    % Prediction 
    % X_pred = F * X_est + G * u
    X_pred = F_ekf * X_est(:, k-1) + G * g;
    P_pred = F_ekf * P_est * F_ekf' + Q_ekf;

    % Update Step 
    Z_measured = measurements_2D(:, k);
    
    [X_updated, P_updated] = EKF_Update_Step(X_pred, P_pred, Z_measured, R_ekf, K_cam, R_GCF_to_Cam, t_GCF_to_Cam);
    
    % Store final estimate
    X_est(:, k) = X_updated;
    P_est       = P_updated;

end
% for k = 2:num_measurements
%     % varying dt 
%     dt = measurement_log(k, 1) - measurement_log(k-1, 1);
% 
%     % CV process model 
%     F_ekf = [1 0 0 dt 0 0; 
%              0 1 0 0 dt 0; 
%              0 0 1 0  0 dt; 
%              0 0 0 1  0 0; 
%              0 0 0 0  1 0; 
%              0 0 0 0  0 1];
% 
%     q_pos = 0.5 * dt^2; 
%     q_vel = 2.0 * dt;   
%     Q_ekf = diag([q_pos, q_pos, q_pos, q_vel, q_vel, q_vel]);
% 
%     X_pred = F_ekf * X_est(:, k-1);
%     P_pred = F_ekf * P_est * F_ekf' + Q_ekf;
% 
%     cam_id = measurement_log(k, 2); % 0 for Cam1, 1 for Cam2
%     Z_measured = measurement_log(k, 3:4)';
% 
%     if cam_id == 0 % Camera 1
%         [X_updated, P_updated] = EKF_Update_Step(X_pred, P_pred, Z_measured, R_ekf, K_cam1, R_GCF_to_Cam1, t_GCF_to_Cam1);
%     else % Camera 2
%         [X_updated, P_updated] = EKF_Update_Step(X_pred, P_pred, Z_measured, R_ekf, K_cam2, R_GCF_to_Cam2, t_GCF_to_Cam2);
%     end
% 
%     X_est(:, k) = X_updated;
%     P_est       = P_updated; 
% end

%% Section 4: Visualization of Final Estimated Trajectory

figure(1); clf;
plot3(X_est(1,:), X_est(2,:), X_est(3,:), 'r.-', 'DisplayName', 'EKF Estimated Path');
hold on;

% Plot the coordinate frame of the two cameras
plotCamera('Size', 0.5, 'Orientation', R_GCF_to_Cam1', 'Location', [0;0;0], 'Label', 'Cam 1');
plotCamera('Size', 0.5, 'Orientation', R_GCF_to_Cam2', 'Location', t_Cam1_to_Cam2, 'Label', 'Cam 2');

xlabel('X (m)'); ylabel('Y (m)'); zlabel('Z (m)');
title('Final Estimated 3D Trajectory from Real Data');
legend; grid on; axis equal; view(30,20);
set(gca, 'ZDir','reverse', 'YDir','reverse');

%% Helper Functions

% project_point acts as a virtual camera, takes a 3D traj point annd
% projects it into (u,v) coordinates. 
function [uv, in_fov] = project_point(point_GCF, R_GCF2Cam, t_GCF2Cam, K_cam, img_width, img_height)
    uv = [NaN; NaN];
    in_fov = false;

    % 1. Get point in camera CF.
    point_camera = R_GCF2Cam * point_GCF + t_GCF2Cam;

    % 2. Check if object is in front of cam
    if point_camera(3) > 0.01

        % 3. Get x and y coords of curr. camera point 
        x_norm = point_camera(1) / point_camera(3);
        y_norm = point_camera(2) / point_camera(3);

        % 4. Find the corresponding homogeneous pixel points (u, v) of this
        % camera point 
        point_homo_norm = [x_norm; y_norm; 1];
        point_pixels_homo = K_cam * point_homo_norm;

        u_value = point_pixels_homo(1);
        v_value = point_pixels_homo(2);

        % 5. Check if these points are within the camera viewing
        % boundaries. 
        if ((u_value >= 0 && u_value < img_width) && (v_value >= 0 && v_value < img_height))
            uv = [u_value; v_value];
            in_fov = true;
        end

    end
end

function [X_updated, P_updated] = EKF_Update_Step(X_pred, P_pred, Z_measured, R_noise, K_cam, R_GCF_to_Cam, t_GCF_to_Cam)
    % Calculate expected measurement h(X_pred)

    % get 3D position from 6D predicted state X_pred since camera
    % measurement only depends on object's 3D position
    P_GCF_pred = X_pred(1:3);

    % transform 3D GCF position into camera LCF
    % P_camera_pred = [Xc_predicted; Yc_predicted; Zc_predicted]
    P_camera_pred = R_GCF_to_Cam * P_GCF_pred + t_GCF_to_Cam;

    % check if EKF predicted point is behind or exactly on camera plane
    if P_camera_pred(3) <= 0.01 
        % No update possible
        X_updated = X_pred; 
        P_updated = P_pred;
        return;
    end

    % Perspective division 
    Xc_val_pred = P_camera_pred(1);
    Yc_val_pred = P_camera_pred(2);
    Zc_val_pred = P_camera_pred(3);
    
    Xc_norm_pred = Xc_val_pred / Zc_val_pred; 
    Yc_norm_pred = Yc_val_pred / Zc_val_pred;

    % expected 2D pixel measurement h(x_hat(k|k-1))
    Z_expected = K_cam * [Xc_norm_pred; Yc_norm_pred; 1];
    % extract u_expected and v_expected 
    Z_expected = Z_expected(1:2);

    % Calculate Jacobian H
    fx = K_cam(1,1);
    fy = K_cam(2,2);

    % Jacobian of pixel projection w.r.t 3D point in camera coords 
    % u = fx * Xc/Zc + cx
    % v = fy * Yc/Zc + cy
    % 2 x 3 matrix 
    dZexpected_dPcamera = [(fx/Zc_val_pred),      0          , (-fx * Xc_val_pred)/(Zc_val_pred^2);
                             0             , (fy/Zc_val_pred), (-fy * Yc_val_pred)/(Zc_val_pred^2)];

    % Jacobian of GCF to camera coord transformation (P_camera_pred w.r.t P_GCF_pred)
    % 3 x 3 matrix
    dPcamera_dPgcf = R_GCF_to_Cam;

    % Jacobain of full camera projection (3D GCF  to 2D pixels):
    % 2 x 3 matrix 
    dZexpected_dPgcf = dZexpected_dPcamera * dPcamera_dPgcf;

    % Full H, since u,v do not depend on vx, vy, vz in 'h' model, their
    % partial derivatives are zero 
    % H = [dZexpected_dPgcf(1,1), dZexpected_dPgcf(1,2), dZexpected_dPgcf(1,3), 0, 0, 0; 
    %      dZexpected_dPgcf(2,1), dZexpected_dPgcf(2,2), dZexpected_dPgcf(2,3), 0, 0, 0 ]; 

    H = [dZexpected_dPgcf, zeros(2, 3)];

    % EKF Update Equations
    Z = Z_measured - Z_expected;
    S = H * P_pred * H' + R_noise;
    K_gain = (P_pred * H') * (S)^(-1);

    X_updated = X_pred + K_gain * Z;
    P_updated = (eye(6) - K_gain * H) * P_pred;
end